apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ktp
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        return 200 "Kantapit Phaengdee";
      } 
    }
